language: python
dist: focal
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
env:
  - CODECOV_TOKEN=$CODECOV_TOKEN
before_install:
  - python -m pip install --upgrade pip
  - pip install poetry codecov
  - poetry config virtualenvs.create false
install:
  - poetry install
script: poetry run pytest --cov-report=term-missing --cov=src --cov-report=xml --junitxml=junit/report.xml --basetemp=tests/unit/tmp tests/
after_success:
  - codecov